# Generated by Django 6.0.2 on 2026-02-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('arquivo_tamanho', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('linhas_total', models.PositiveIntegerField(default=0, verbose_name='Total de linhas')),
                ('linhas_processadas', models.PositiveIntegerField(default=0, verbose_name='Linhas processadas')),
                ('linhas_com_valor', models.PositiveIntegerField(default=0, verbose_name='Linhas com valor')),
                ('linhas_sem_match', models.PositiveIntegerField(default=0, verbose_name='Linhas sem match')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor total calculado')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], default='sucesso', max_length=10, verbose_name='Status')),
                ('erro_mensagem', models.TextField(blank=True, default='', verbose_name='Mensagem de erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data do processamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processamentos_vigilante', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Processamento',
                'verbose_name_plural': 'Processamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
