# Generated by Django 5.2.6 on 2025-09-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20250903_1732'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Telefone Alternativo')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, choices=[('TI', 'Tecnologia da Informação'), ('SUP', 'Suporte Técnico'), ('RH', 'Recursos Humanos'), ('FIN', 'Financeiro'), ('OPS', 'Operações'), ('COM', 'Comercial')], max_length=3, verbose_name='Departamento')),
                ('bio', models.TextField(blank=True, verbose_name='Bio Profissional')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
