# Generated by Django 5.2.6 on 2025-09-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Automação',
                'verbose_name_plural': 'Configurações de Automação',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_tickets', models.IntegerField(default=0)),
                ('new_tickets', models.IntegerField(default=0)),
                ('resolved_tickets', models.IntegerField(default=0)),
                ('sla_compliance_rate', models.FloatField(default=0.0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('agent_productivity', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métricas do Sistema',
                'verbose_name_plural': 'Métricas do Sistema',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trigger_event', models.CharField(choices=[('ticket_created', 'Ticket Criado'), ('ticket_updated', 'Ticket Atualizado'), ('status_changed', 'Status Alterado'), ('agent_assigned', 'Agente Atribuído'), ('interaction_added', 'Interação Adicionada'), ('sla_warning', 'Aviso de SLA'), ('sla_breach', 'Violação de SLA')], max_length=50)),
                ('conditions', models.JSONField(help_text='Condições em formato JSON')),
                ('actions', models.JSONField(help_text='Ações em formato JSON')),
                ('priority', models.IntegerField(default=1, help_text='Prioridade de execução (1-10)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Workflow',
                'verbose_name_plural': 'Regras de Workflow',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='origem',
            field=models.CharField(default='web', help_text='web, email, whatsapp, slack', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Prazo de resposta SLA', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_agente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categoriaticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dashboard.cliente'),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.JSONField(help_text='Lista de palavras-chave para busca')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('unhelpful_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base de Conhecimento',
                'verbose_name_plural': 'Base de Conhecimento',
                'ordering': ['-view_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('bounced', 'Rejeitado')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('response_time_hours', models.IntegerField(help_text='Tempo de resposta em horas')),
                ('resolution_time_hours', models.IntegerField(blank=True, help_text='Tempo de resolução em horas', null=True)),
                ('business_hours_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.categoriaticket')),
            ],
            options={
                'verbose_name': 'Política de SLA',
                'verbose_name_plural': 'Políticas de SLA',
            },
        ),
        migrations.CreateModel(
            name='SLAViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('deadline_missed', 'Prazo Perdido'), ('escalation_failed', 'Falha na Escalação'), ('response_delayed', 'Resposta Atrasada')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('expected_deadline', models.DateTimeField()),
                ('actual_time', models.DateTimeField()),
                ('time_exceeded', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_violations', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Violação de SLA',
                'verbose_name_plural': 'Violações de SLA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_event', models.CharField(max_length=50)),
                ('execution_result', models.JSONField()),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='dashboard.ticket')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workflowrule')),
            ],
            options={
                'verbose_name': 'Execução de Workflow',
                'verbose_name_plural': 'Execuções de Workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
