# Generated by Django 5.2.6 on 2025-09-09 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_automationsettings_systemmetrics_workflowrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500),
        ),
        migrations.CreateModel(
            name='TicketAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tickets/anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.BigIntegerField(help_text='Tamanho em bytes')),
                ('tipo_mime', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Anexo do Ticket',
                'verbose_name_plural': 'Anexos dos Tickets',
            },
        ),
    ]
