# Generated by Django 5.2.6 on 2025-09-11 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ticket_tags_ticketanexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_ticket', 'Novo Ticket'), ('ticket_assigned', 'Ticket Atribuído'), ('ticket_status_change', 'Mudança de Status'), ('sla_warning', 'Alerta de SLA'), ('new_interaction', 'Nova Interação'), ('system_alert', 'Alerta do Sistema')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='notifications', max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Primária'), ('secondary', 'Secundária'), ('success', 'Sucesso'), ('danger', 'Perigo'), ('warning', 'Aviso'), ('info', 'Informação')], default='primary', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_n_user_id_5c2164_idx'), models.Index(fields=['read', '-created_at'], name='dashboard_n_read_8fa9de_idx')],
            },
        ),
    ]
