# Generated by Django 5.2.6 on 2025-09-12 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('categoria', 'prioridade')},
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='end_hour',
            field=models.TimeField(default='18:00', help_text='Fim do horário comercial'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='escalation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='escalation_time',
            field=models.IntegerField(default=480, help_text='Tempo para escalação em minutos'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='escalation_to',
            field=models.ForeignKey(blank=True, help_text='Supervisor para escalação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='first_response_time',
            field=models.IntegerField(default=240, help_text='Tempo primeira resposta em minutos'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='resolution_time',
            field=models.IntegerField(default=1440, help_text='Tempo de resolução em minutos'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='start_hour',
            field=models.TimeField(default='08:00', help_text='Início do horário comercial'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='warning_percentage',
            field=models.IntegerField(default=80, help_text='% do tempo SLA para enviar alerta'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='work_days',
            field=models.CharField(default='1234567', help_text='Dias da semana (1=Seg, 7=Dom)', max_length=7),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.slapolicy'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_deadline',
            field=models.DateTimeField(blank=True, help_text='Prazo de resolução SLA', null=True),
        ),
        migrations.CreateModel(
            name='SLAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_response_deadline', models.DateTimeField()),
                ('resolution_deadline', models.DateTimeField()),
                ('escalation_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('on_track', 'No Prazo'), ('warning', 'Alerta'), ('breached', 'Violado'), ('escalated', 'Escalado'), ('completed', 'Concluído')], default='on_track', max_length=15)),
                ('warning_sent', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_time', models.DurationField(blank=True, null=True)),
                ('resolution_time', models.DurationField(blank=True, null=True)),
                ('sla_compliance', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.slapolicy')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_history', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Histórico de SLA',
                'verbose_name_plural': 'Históricos de SLA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('warning', 'Alerta de Prazo'), ('breach', 'Violação de SLA'), ('escalation', 'Escalação Necessária'), ('resolved', 'SLA Cumprido')], max_length=15)),
                ('message', models.TextField()),
                ('sent_to_agent', models.BooleanField(default=False)),
                ('sent_to_supervisor', models.BooleanField(default=False)),
                ('sent_to_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_alerts', to='dashboard.ticket')),
                ('sla_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.slahistory')),
            ],
            options={
                'verbose_name': 'Alerta de SLA',
                'verbose_name_plural': 'Alertas de SLA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='slapolicy',
            name='resolution_time_hours',
        ),
        migrations.RemoveField(
            model_name='slapolicy',
            name='response_time_hours',
        ),
    ]
