# Generated by Django 5.2.6 on 2025-09-12 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_slapolicy_unique_together_slapolicy_end_hour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='iConnect Assistant', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('greeting_message', models.TextField(default='Olá! Sou o assistente virtual da iConnect. Como posso ajudar?')),
                ('fallback_message', models.TextField(default='Desculpe, não entendi. Posso conectá-lo com um agente humano?')),
                ('handoff_keywords', models.TextField(default='agente,humano,pessoa,atendente', help_text='Palavras-chave separadas por vírgula para transferir para agente humano')),
                ('openai_model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('max_tokens', models.PositiveIntegerField(default=150)),
                ('temperature', models.FloatField(default=0.7)),
                ('business_hours_start', models.TimeField(default='08:00')),
                ('business_hours_end', models.TimeField(default='18:00')),
                ('weekend_active', models.BooleanField(default=False)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('successful_resolutions', models.PositiveIntegerField(default=0)),
                ('handoffs_to_agents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ChatBot',
                'verbose_name_plural': 'ChatBots',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Sala')),
                ('room_type', models.CharField(choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas'), ('general', 'Geral'), ('group', 'Grupo'), ('private', 'Privado')], default='support', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('closed', 'Fechado'), ('archived', 'Arquivado')], default='active', max_length=20)),
                ('is_private', models.BooleanField(default=True, verbose_name='Chat Privado')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Máximo de Participantes')),
                ('allow_file_upload', models.BooleanField(default=True, verbose_name='Permitir Upload de Arquivos')),
                ('allow_voice_messages', models.BooleanField(default=True, verbose_name='Permitir Mensagens de Voz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ticket', verbose_name='Ticket Relacionado')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('file', 'Arquivo'), ('image', 'Imagem'), ('voice', 'Voz'), ('video', 'Vídeo'), ('system', 'Sistema'), ('location', 'Localização'), ('contact', 'Contato')], default='text', max_length=20)),
                ('content', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('formatted_content', models.TextField(blank=True, verbose_name='Conteúdo Formatado')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt', 'mp3', 'mp4', 'wav', 'ogg'])])),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamanho em bytes')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='dashboard.chatmessage', verbose_name='Encaminhada de')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='dashboard.chatmessage', verbose_name='Resposta a')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.chatroom')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('sound_notifications', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='light', max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], default='medium', max_length=10)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_typing_indicator', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('auto_response_enabled', models.BooleanField(default=False)),
                ('auto_response_message', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurações de Chat',
                'verbose_name_plural': 'Configurações de Chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='dashboard.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmação de Leitura',
                'verbose_name_plural': 'Confirmações de Leitura',
                'ordering': ['read_at'],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('😂', 'Laugh'), ('😮', 'Surprise'), ('😢', 'Sad'), ('😡', 'Angry'), ('👏', 'Clap'), ('🔥', 'Fire')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='dashboard.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['created_at'],
                'unique_together': {('message', 'user', 'reaction')},
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('agent', 'Agente'), ('client', 'Cliente'), ('observer', 'Observador')], default='client', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_typing', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_participants', to='dashboard.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.chatroom')),
            ],
            options={
                'verbose_name': 'Participante do Chat',
                'verbose_name_plural': 'Participantes do Chat',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='dashboard_c_room_id_896588_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='dashboard_c_sender__5a3598_idx'),
        ),
    ]
