# Generated by Django 5.2.6 on 2025-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_categoriafinanceira_formapagamento_contrato_fatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDeVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Municipal')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=120, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=60, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('pais', models.CharField(default='Brasil', max_length=40, verbose_name='País')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular / WhatsApp')),
                ('email_principal', models.EmailField(max_length=254, verbose_name='E-mail principal')),
                ('email_financeiro', models.EmailField(blank=True, max_length=254, verbose_name='E-mail financeiro')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('responsavel_nome', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('responsavel_cpf', models.CharField(max_length=14, verbose_name='CPF do Responsável')),
                ('responsavel_cargo', models.CharField(max_length=60, verbose_name='Cargo / Função')),
                ('responsavel_telefone', models.CharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('responsavel_email', models.EmailField(max_length=254, verbose_name='E-mail do Responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ponto de Venda',
                'verbose_name_plural': 'Pontos de Venda',
                'ordering': ['-criado_em'],
            },
        ),
    ]
