# Generated by Django 5.2.6 on 2025-10-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_apply_improvements'),
        ('dashboard', '0010_pontodevenda'),
    ]

    operations = [
    ]
