# Generated by Django 5.2.6 on 2025-10-01 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_merge_0009_apply_improvements_0010_pontodevenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDashboardKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do KPI')),
                ('kpi_type', models.CharField(choices=[('tickets_volume', 'Volume de Tickets'), ('sla_compliance', 'Compliance SLA'), ('customer_satisfaction', 'Satisfação do Cliente'), ('agent_productivity', 'Produtividade dos Agentes'), ('resolution_time', 'Tempo de Resolução'), ('first_contact_resolution', 'Resolução no Primeiro Contato'), ('cost_per_ticket', 'Custo por Ticket'), ('revenue_impact', 'Impacto na Receita')], max_length=50, verbose_name='Tipo de KPI')),
                ('target_value', models.FloatField(verbose_name='Meta')),
                ('current_value', models.FloatField(default=0, verbose_name='Valor Atual')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Executivo',
                'verbose_name_plural': 'KPIs Executivos',
            },
        ),
        migrations.CreateModel(
            name='PesquisaSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_atendimento', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('nota_resolucao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('nota_tempo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('widget_type', models.CharField(choices=[('chart_line', 'Gráfico de Linha'), ('chart_bar', 'Gráfico de Barras'), ('chart_pie', 'Gráfico de Pizza'), ('metric_card', 'Card de Métrica'), ('table', 'Tabela'), ('progress_bar', 'Barra de Progresso'), ('heat_map', 'Mapa de Calor')], max_length=20, verbose_name='Tipo')),
                ('data_source', models.CharField(max_length=100, verbose_name='Fonte de Dados')),
                ('config', models.JSONField(default=dict, verbose_name='Configuração')),
                ('position_x', models.IntegerField(default=0, verbose_name='Posição X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Posição Y')),
                ('width', models.IntegerField(default=4, verbose_name='Largura')),
                ('height', models.IntegerField(default=3, verbose_name='Altura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Widget do Dashboard',
                'verbose_name_plural': 'Widgets do Dashboard',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='AlertaKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', 'Limite'), ('trend', 'Tendência'), ('anomaly', 'Anomalia')], max_length=20, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, verbose_name='Severidade')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Valor Limite')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.executivedashboardkpi', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Alerta KPI',
                'verbose_name_plural': 'Alertas KPI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricaTempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50, verbose_name='Nome da Métrica')),
                ('value', models.JSONField(verbose_name='Valor')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('category', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Métrica Tempo Real',
                'verbose_name_plural': 'Métricas Tempo Real',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='dashboard_m_metric__441d35_idx'), models.Index(fields=['category', 'timestamp'], name='dashboard_m_categor_0cc2f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.BooleanField(default=True, verbose_name='Notificações de Tickets')),
                ('chat', models.BooleanField(default=True, verbose_name='Notificações de Chat')),
                ('system', models.BooleanField(default=True, verbose_name='Notificações do Sistema')),
                ('quiet_hours', models.BooleanField(default=False, verbose_name='Horário Silencioso')),
                ('quiet_start', models.TimeField(blank=True, null=True, verbose_name='Início do Silêncio')),
                ('quiet_end', models.TimeField(blank=True, null=True, verbose_name='Fim do Silêncio')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Som Habilitado')),
                ('vibration_enabled', models.BooleanField(default=True, verbose_name='Vibração Habilitada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
                'db_table': 'dashboard_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='PerguntaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('tipo', models.CharField(choices=[('rating', 'Avaliação (1-5)'), ('nps', 'NPS (0-10)'), ('multipla', 'Múltipla Escolha'), ('texto', 'Texto Livre')], max_length=20)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pesquisasatisfacao')),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh_key', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'db_table': 'dashboard_push_subscription',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(default='system', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('clicked', 'Clicada'), ('dismissed', 'Dispensada')], default='pending', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pushsubscription')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificação',
                'db_table': 'dashboard_notification_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='dashboard_n_user_id_e7eaf4_idx'), models.Index(fields=['notification_type', 'created_at'], name='dashboard_n_notific_74c828_idx')],
            },
        ),
    ]
