# Generated by Django 5.2.6 on 2025-10-01 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_executivedashboardkpi_pesquisasatisfacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('total_conversas', models.IntegerField(default=0, verbose_name='Total de Conversas')),
                ('total_mensagens', models.IntegerField(default=0, verbose_name='Total de Mensagens')),
                ('respostas_automaticas', models.IntegerField(default=0, verbose_name='Respostas Automáticas')),
                ('transferencias_humano', models.IntegerField(default=0, verbose_name='Transferências para Humano')),
                ('satisfacao_media', models.FloatField(blank=True, null=True, verbose_name='Satisfação Média')),
                ('tempo_resposta_medio', models.FloatField(blank=True, null=True, verbose_name='Tempo Resposta Médio (s)')),
            ],
            options={
                'verbose_name': 'Analytics Chatbot',
                'verbose_name_plural': 'Analytics Chatbot',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['data'], name='dashboard_c_data_eca369_idx')],
                'unique_together': {('data',)},
            },
        ),
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('string', 'String'), ('integer', 'Inteiro'), ('float', 'Decimal'), ('boolean', 'Booleano'), ('json', 'JSON')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração Chatbot',
                'verbose_name_plural': 'Configurações Chatbot',
                'ordering': ['nome'],
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('contexto', models.JSONField(default=dict, verbose_name='Contexto da Conversa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conversa Chatbot',
                'verbose_name_plural': 'Conversas Chatbot',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags (separadas por vírgula)')),
                ('confianca', models.FloatField(default=1.0, verbose_name='Nível de Confiança')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Base de Conhecimento',
                'verbose_name_plural': 'Base de Conhecimento',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['categoria', 'ativo'], name='dashboard_c_categor_7fdedb_idx'), models.Index(fields=['tags'], name='dashboard_c_tags_bee4dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot'), ('system', 'Sistema')], max_length=10, verbose_name='Tipo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('confianca', models.FloatField(blank=True, null=True, verbose_name='Confiança da Resposta')),
                ('metadados', models.JSONField(default=dict, verbose_name='Metadados')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='dashboard.chatbotconversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem Chatbot',
                'verbose_name_plural': 'Mensagens Chatbot',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_original', models.TextField(verbose_name='Pergunta Original')),
                ('resposta_bot', models.TextField(verbose_name='Resposta do Bot')),
                ('resposta_esperada', models.TextField(blank=True, verbose_name='Resposta Esperada')),
                ('feedback_positivo', models.BooleanField(blank=True, null=True, verbose_name='Feedback Positivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Treinamento Chatbot',
                'verbose_name_plural': 'Treinamentos Chatbot',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbotconversation',
            index=models.Index(fields=['session_id', 'ativa'], name='dashboard_c_session_0fac25_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotconversation',
            index=models.Index(fields=['usuario', '-iniciada_em'], name='dashboard_c_usuario_1540ad_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['conversa', 'timestamp'], name='dashboard_c_convers_cc73d7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['tipo', 'timestamp'], name='dashboard_c_tipo_b6d1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbottraining',
            index=models.Index(fields=['processado', '-criado_em'], name='dashboard_c_process_a65f45_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbottraining',
            index=models.Index(fields=['feedback_positivo'], name='dashboard_c_feedbac_54673e_idx'),
        ),
    ]
