# Generated by Django 5.2.6 on 2025-10-01 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_chatbotanalytics_chatbotconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('phone_number_id', models.CharField(max_length=50, unique=True, verbose_name='Phone Number ID')),
                ('business_account_id', models.CharField(max_length=50, verbose_name='Business Account ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('webhook_verify_token', models.CharField(max_length=255, verbose_name='Webhook Verify Token')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conta WhatsApp Business',
                'verbose_name_plural': 'Contas WhatsApp Business',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=50, unique=True, verbose_name='WhatsApp ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('profile_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Perfil')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags')),
                ('metadados', models.JSONField(default=dict, verbose_name='Metadados')),
                ('primeiro_contato', models.DateTimeField(auto_now_add=True, verbose_name='Primeiro Contato')),
                ('ultimo_contato', models.DateTimeField(auto_now=True, verbose_name='Último Contato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Vinculado')),
            ],
            options={
                'verbose_name': 'Contato WhatsApp',
                'verbose_name_plural': 'Contatos WhatsApp',
                'ordering': ['-ultimo_contato'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada'), ('transferida', 'Transferida')], default='ativa', max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('encerrada_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrada em')),
                ('contexto', models.JSONField(default=dict, verbose_name='Contexto')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappbusinessaccount', verbose_name='Conta')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agente Responsável')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappcontact', verbose_name='Contato')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ticket', verbose_name='Ticket Vinculado')),
            ],
            options={
                'verbose_name': 'Conversa WhatsApp',
                'verbose_name_plural': 'Conversas WhatsApp',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(max_length=100, unique=True, verbose_name='WhatsApp Message ID')),
                ('direcao', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], max_length=10, verbose_name='Direção')),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Localização'), ('contact', 'Contato'), ('interactive', 'Interativo'), ('template', 'Template'), ('system', 'Sistema')], max_length=20, verbose_name='Tipo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('media_url', models.URLField(blank=True, verbose_name='URL da Mídia')),
                ('media_mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type da Mídia')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadados')),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='sent', max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('processada', models.BooleanField(default=False, verbose_name='Processada')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappcontact', verbose_name='Contato')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='dashboard.whatsappconversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utilidade'), ('authentication', 'Autenticação')], max_length=20, verbose_name='Categoria')),
                ('idioma', models.CharField(default='pt_BR', max_length=10, verbose_name='Idioma')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('pending', 'Pendente'), ('rejected', 'Rejeitado'), ('disabled', 'Desabilitado')], default='pending', max_length=20, verbose_name='Status')),
                ('conteudo', models.JSONField(verbose_name='Conteúdo do Template')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappbusinessaccount', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAutoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_trigger', models.CharField(choices=[('keyword', 'Palavra-chave'), ('first_message', 'Primeira mensagem'), ('business_hours', 'Fora do horário'), ('agent_unavailable', 'Agente indisponível')], max_length=20, verbose_name='Tipo de Gatilho')),
                ('trigger_value', models.CharField(blank=True, max_length=200, verbose_name='Valor do Gatilho')),
                ('mensagem_texto', models.TextField(blank=True, verbose_name='Mensagem de Texto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappbusinessaccount', verbose_name='Conta')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsapptemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Resposta Automática WhatsApp',
                'verbose_name_plural': 'Respostas Automáticas WhatsApp',
                'ordering': ['-prioridade', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('message', 'Mensagem'), ('status', 'Status'), ('notification', 'Notificação'), ('error', 'Erro')], max_length=20, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappbusinessaccount', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Log Webhook WhatsApp',
                'verbose_name_plural': 'Logs Webhook WhatsApp',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('mensagens_enviadas', models.IntegerField(default=0, verbose_name='Mensagens Enviadas')),
                ('mensagens_recebidas', models.IntegerField(default=0, verbose_name='Mensagens Recebidas')),
                ('mensagens_entregues', models.IntegerField(default=0, verbose_name='Mensagens Entregues')),
                ('mensagens_lidas', models.IntegerField(default=0, verbose_name='Mensagens Lidas')),
                ('conversas_iniciadas', models.IntegerField(default=0, verbose_name='Conversas Iniciadas')),
                ('conversas_encerradas', models.IntegerField(default=0, verbose_name='Conversas Encerradas')),
                ('tickets_criados', models.IntegerField(default=0, verbose_name='Tickets Criados')),
                ('tempo_resposta_medio', models.FloatField(blank=True, null=True, verbose_name='Tempo Resposta Médio (min)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.whatsappbusinessaccount', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Analytics WhatsApp',
                'verbose_name_plural': 'Analytics WhatsApp',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['account', '-data'], name='dashboard_w_account_b31f3e_idx')],
                'unique_together': {('account', 'data')},
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['whatsapp_id'], name='dashboard_w_whatsap_f554cb_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['phone_number'], name='dashboard_w_phone_n_7e611c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['-ultimo_contato'], name='dashboard_w_ultimo__d85b63_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['account', 'contact', '-iniciada_em'], name='dashboard_w_account_38df8d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['estado', '-iniciada_em'], name='dashboard_w_estado_730e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['agente', '-iniciada_em'], name='dashboard_w_agente__880256_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='dashboard_w_convers_1a9820_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['contact', '-timestamp'], name='dashboard_w_contact_2bd3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['direcao', 'status'], name='dashboard_w_direcao_e31038_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['processada', 'timestamp'], name='dashboard_w_process_a285c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsapptemplate',
            unique_together={('account', 'nome')},
        ),
        migrations.AddIndex(
            model_name='whatsappwebhooklog',
            index=models.Index(fields=['account', '-timestamp'], name='dashboard_w_account_1ddc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappwebhooklog',
            index=models.Index(fields=['processado', 'timestamp'], name='dashboard_w_process_a2da02_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappwebhooklog',
            index=models.Index(fields=['tipo_evento', '-timestamp'], name='dashboard_w_tipo_ev_f94312_idx'),
        ),
    ]
