# Generated by Django 5.2.6 on 2025-10-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_whatsapp_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='data_movimentacao',
            field=models.DateField(help_text='Data da movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='fatura',
            field=models.ForeignKey(blank=True, help_text='Fatura relacionada (para receitas de faturas pagas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fatura'),
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do centro de custo', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome do centro de custo', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada', null=True)),
                ('departamento', models.CharField(help_text='Departamento responsável', max_length=100)),
                ('orcamento_mensal', models.DecimalField(decimal_places=2, default=0, help_text='Orçamento mensal planejado', max_digits=12)),
                ('orcamento_anual', models.DecimalField(decimal_places=2, default=0, help_text='Orçamento anual planejado', max_digits=12)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], default='ativo', max_length=20)),
                ('permite_suborçamento', models.BooleanField(default=False, help_text='Permite estourar o orçamento')),
                ('alerta_percentual', models.DecimalField(decimal_places=2, default=80, help_text='Percentual para alerta de orçamento (%)', max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('centro_pai', models.ForeignKey(blank=True, help_text='Centro de custo pai (para hierarquia)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcentros', to='dashboard.centrocusto')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_custo_criados', to=settings.AUTH_USER_MODEL)),
                ('gerente', models.ForeignKey(blank=True, help_text='Gerente do centro de custo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_custo_gerente', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, help_text='Responsável pelo centro de custo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_custo_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['departamento', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='centro_custo',
            field=models.ForeignKey(blank=True, help_text='Centro de custo responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='dashboard.centrocusto'),
        ),
    ]
