# Generated by Django 5.2.6 on 2025-10-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_movimentacaofinanceira_data_movimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='data_movimentacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fatura'),
        ),
    ]
