# Generated by Django 5.2.6 on 2025-10-01 20:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_movimentacaofinanceira_data_movimentacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', help_text='Cor em hexadecimal', max_length=7)),
                ('icone', models.CharField(default='inventory', help_text='Ícone Material Design', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('controla_estoque', models.BooleanField(default=True, help_text='Se deve controlar estoque para esta categoria')),
                ('permite_estoque_negativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Estoque',
                'verbose_name_plural': 'Categorias de Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno do fornecedor', max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='juridica', max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo_operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferência')], max_length=15)),
                ('descricao', models.TextField(blank=True)),
                ('automatico', models.BooleanField(default=False, help_text='Criado automaticamente pelo sistema')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimentação',
                'verbose_name_plural': 'Tipos de Movimentação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('peso', 'Peso'), ('volume', 'Volume'), ('comprimento', 'Comprimento'), ('area', 'Área'), ('unidade', 'Unidade'), ('tempo', 'Tempo'), ('outros', 'Outros')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='SKU/Código do produto', max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('produto', 'Produto Físico'), ('servico', 'Serviço'), ('kit', 'Kit/Combo')], default='produto', max_length=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de margem', max_digits=5)),
                ('controla_estoque', models.BooleanField(default=True)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('localizacao', models.CharField(blank=True, help_text='Endereço no estoque', max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=15)),
                ('permite_venda_sem_estoque', models.BooleanField(default=False)),
                ('peso', models.DecimalField(decimal_places=3, default=0, help_text='Peso em Kg', max_digits=8)),
                ('altura', models.DecimalField(decimal_places=2, default=0, help_text='Altura em cm', max_digits=8)),
                ('largura', models.DecimalField(decimal_places=2, default=0, help_text='Largura em cm', max_digits=8)),
                ('profundidade', models.DecimalField(decimal_places=2, default=0, help_text='Profundidade em cm', max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.categoriaestoque')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fornecedor')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.unidademedida')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('estoque_critico', 'Estoque Crítico'), ('estoque_zerado', 'Estoque Zerado'), ('produto_inativo', 'Produto Inativo')], max_length=20)),
                ('mensagem', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('data_alerta', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produto')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'ordering': ['-data_alerta'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferência')], max_length=15)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estoque_anterior', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('estoque_posterior', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('numero_documento', models.CharField(blank=True, help_text='Número da NF, pedido, etc.', max_length=50)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True, help_text='Justificativa para ajustes')),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fornecedor')),
                ('ticket_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.produto')),
                ('tipo_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.tipomovimentacao')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['numero'], name='dashboard_m_numero_5ab491_idx'), models.Index(fields=['produto', '-data_movimentacao'], name='dashboard_m_produto_91d06c_idx'), models.Index(fields=['tipo_operacao', '-data_movimentacao'], name='dashboard_m_tipo_op_0423e6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo'], name='dashboard_p_codigo_0c0755_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo_barras'], name='dashboard_p_codigo__502cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='dashboard_p_categor_366d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['status'], name='dashboard_p_status_e46a1d_idx'),
        ),
    ]
