# Generated by Django 5.2.6 on 2025-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_categoriaestoque_fornecedor_tipomovimentacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='estoque_posterior',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='estoque_apos_movimentacao',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='estoque_anterior',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
    ]
