# Generated by Django 5.2.7 on 2025-10-08 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_movimentacaoestoque_estoque_posterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='produto', max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário usado no atendimento', max_digits=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado (%)', max_digits=5)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o uso do item no atendimento')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_adicionados', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_atendimento', to='dashboard.produto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_atendimento', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Item de Atendimento',
                'verbose_name_plural': 'Itens de Atendimento',
                'ordering': ['adicionado_em'],
                'unique_together': {('ticket', 'produto')},
            },
        ),
    ]
