# Generated by Django 5.2.6 on 2026-02-22 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_itematendimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-view_count', '-created_at'], 'verbose_name': 'Base de Conhecimento (Deprecado)', 'verbose_name_plural': 'Base de Conhecimento (Deprecado)'},
        ),
        migrations.AddField(
            model_name='interacaoticket',
            name='canal',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('chat', 'Chat'), ('api', 'API')], default='web', max_length=15),
        ),
        migrations.AddField(
            model_name='interacaoticket',
            name='tipo',
            field=models.CharField(choices=[('resposta', 'Resposta'), ('nota_interna', 'Nota Interna'), ('sistema', 'Sistema'), ('status_change', 'Mudança de Status')], db_index=True, default='resposta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando_cliente', 'Aguardando Cliente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], db_index=True, default='aberto', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interacaoticket',
            index=models.Index(fields=['ticket', 'criado_em'], name='dashboard_i_ticket__ec1ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaoticket',
            index=models.Index(fields=['tipo', 'criado_em'], name='dashboard_i_tipo_d69493_idx'),
        ),
    ]
