# Generated by Django 5.2.6 on 2026-02-22 00:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0020_alter_knowledgebase_options_interacaoticket_canal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Criacao'), ('update', 'Atualizacao'), ('delete', 'Exclusao'), ('view', 'Visualizacao'), ('export', 'Exportacao'), ('import', 'Importacao'), ('permission_change', 'Mudanca de Permissao'), ('security_event', 'Evento de Seguranca'), ('system_event', 'Evento do Sistema')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='low', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_agent', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('gdpr', 'GDPR'), ('lgpd', 'LGPD'), ('sox', 'SOX'), ('iso27001', 'ISO 27001'), ('custom', 'Personalizado')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('report_data', models.JSONField(default=dict)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatorio de Compliance',
                'verbose_name_plural': 'Relatorios de Compliance',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'Visualizacao'), ('export', 'Exportacao'), ('download', 'Download'), ('print', 'Impressao'), ('copy', 'Copia')], max_length=10)),
                ('data_type', models.CharField(max_length=50)),
                ('record_count', models.PositiveIntegerField(default=1)),
                ('sensitive_fields', models.JSONField(default=list)),
                ('business_justification', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_data_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso a Dados',
                'verbose_name_plural': 'Logs de Acesso a Dados',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('brute_force', 'Tentativa de Forca Bruta'), ('suspicious_login', 'Login Suspeito'), ('privilege_escalation', 'Escalacao de Privilegios'), ('data_breach', 'Possivel Vazamento de Dados'), ('unusual_activity', 'Atividade Incomum'), ('failed_authentication', 'Falha de Autenticacao'), ('permission_denied', 'Acesso Negado')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('investigating', 'Investigando'), ('resolved', 'Resolvido'), ('false_positive', 'Falso Positivo')], default='open', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_events', models.ManyToManyField(blank=True, related_name='alerts', to='dashboard.auditevent')),
            ],
            options={
                'verbose_name': 'Alerta de Seguranca',
                'verbose_name_plural': 'Alertas de Seguranca',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('agente', 'Agente'), ('cliente', 'Cliente')], default='agente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['timestamp', 'event_type'], name='dashboard_a_timesta_b596b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'timestamp'], name='dashboard_a_user_id_b0769d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'timestamp'], name='dashboard_a_ip_addr_f3b951_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['is_suspicious'], name='dashboard_a_is_susp_48e940_idx'),
        ),
    ]
