# Generated by Django 5.2.6 on 2026-02-22 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auditevent_compliancereport_dataaccesslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('date', 'Data'), ('select', 'Selecao'), ('checkbox', 'Checkbox'), ('textarea', 'Area de texto')], max_length=10)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Lista de opcoes para tipo select')),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo Customizado',
                'verbose_name_plural': 'Campos Customizados',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Ticket de destino do merge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='dashboard.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket pai (sub-tickets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tickets', to='dashboard.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_tickets',
            field=models.ManyToManyField(blank=True, help_text='Tickets vinculados', to='dashboard.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisicao de Servico'), ('problema', 'Problema'), ('mudanca', 'Mudanca')], default='incidente', max_length=15),
        ),
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que acompanham este ticket', related_name='watched_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sla_resolution_deadline',
            field=models.DateTimeField(blank=True, help_text='Prazo de resolucao SLA', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por virgula', max_length=500),
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('corpo', models.TextField(help_text='Suporta variaveis: {{cliente_nome}}, {{ticket_numero}}, {{agente_nome}}')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('atalho', models.CharField(blank=True, help_text='Atalho de teclado, ex: /saudacao', max_length=50)),
                ('compartilhado', models.BooleanField(default=True, help_text='Visivel para todos os agentes')),
                ('uso_count', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta Pronta',
                'verbose_name_plural': 'Respostas Prontas',
                'ordering': ['-uso_count', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando_cliente', 'Aguardando Cliente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], max_length=20)),
                ('to_status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('aguardando_cliente', 'Aguardando Cliente'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], max_length=20)),
                ('requires_role', models.CharField(blank=True, help_text='Role necessaria: admin, supervisor, agente', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transicao de Status',
                'verbose_name_plural': 'Transicoes de Status',
                'unique_together': {('from_status', 'to_status')},
            },
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('titulo_padrao', models.CharField(blank=True, max_length=200)),
                ('descricao_padrao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisicao de Servico'), ('problema', 'Problema'), ('mudanca', 'Mudanca')], default='incidente', max_length=15)),
                ('tags_padrao', models.CharField(blank=True, max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categoriaticket')),
            ],
            options={
                'verbose_name': 'Template de Ticket',
                'verbose_name_plural': 'Templates de Ticket',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TicketCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customfield')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Valor de Campo Customizado',
                'verbose_name_plural': 'Valores de Campos Customizados',
                'unique_together': {('ticket', 'field')},
            },
        ),
    ]
