# Generated by Django 5.2.6 on 2026-02-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_aiconfiguration_emailtemplate_escalationchain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_ticket', 'Novo Ticket'), ('ticket_assigned', 'Ticket Atribuído'), ('ticket_status_change', 'Mudança de Status'), ('ticket_update', 'Ticket Atualizado'), ('sla_warning', 'Alerta de SLA'), ('sla_breach', 'SLA Violado'), ('new_interaction', 'Nova Interação'), ('new_message', 'Nova Mensagem'), ('new_response', 'Nova Resposta'), ('system_alert', 'Alerta do Sistema')], max_length=30),
        ),
    ]
