# Generated by Django 5.2.6 on 2026-02-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_add_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_ticket', 'Novo Ticket'), ('ticket_assigned', 'Ticket Atribuído'), ('ticket_status_change', 'Mudança de Status'), ('sla_warning', 'Alerta de SLA'), ('sla_breach', 'SLA Violado'), ('new_interaction', 'Nova Interação'), ('system_alert', 'Alerta do Sistema')], max_length=30),
        ),
    ]
