# Generated by Django 5.2.6 on 2026-02-22 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_consolidate_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='api_key',
            field=models.CharField(help_text='Chave de API (armazenada criptografada)', max_length=500),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='centro_pai',
            field=models.ForeignKey(blank=True, help_text='Centro de custo pai (para hierarquia)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcentros', to='dashboard.centrocusto'),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='orcamento_anual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Orçamento anual planejado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='orcamento_mensal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Orçamento mensal planejado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='dashboard.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(help_text='Senha (armazenada criptografada)', max_length=500),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='dashboard.contrato'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='itematendimento',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='itematendimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='itematendimento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Valor unitário usado no atendimento', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='dashboard.fatura'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(blank=True, help_text='HMAC secret para assinatura (armazenado criptografado)', max_length=500),
        ),
        migrations.AlterField(
            model_name='whatsappbusinessaccount',
            name='access_token',
            field=models.TextField(help_text='Armazenado criptografado', verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='whatsappbusinessaccount',
            name='webhook_verify_token',
            field=models.CharField(help_text='Armazenado criptografado', max_length=500, verbose_name='Webhook Verify Token'),
        ),
    ]
