# Generated by Django 5.2.6 on 2026-02-22 15:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_aiconfiguration_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGPDAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Visualização'), ('export', 'Exportação'), ('edit', 'Edição'), ('delete', 'Exclusão'), ('share', 'Compartilhamento'), ('decrypt', 'Descriptografia')], max_length=10, verbose_name='Ação')),
                ('resource_type', models.CharField(help_text='Ex: Cliente, Fornecedor, PontoDeVenda', max_length=100, verbose_name='Tipo do recurso')),
                ('resource_id', models.CharField(max_length=50, verbose_name='ID do recurso')),
                ('fields_accessed', models.JSONField(default=list, help_text='Lista de campos PII acessados', verbose_name='Campos acessados')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('justification', models.TextField(blank=True, verbose_name='Justificativa')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/hora')),
            ],
            options={
                'verbose_name': 'Log de Acesso PII',
                'verbose_name_plural': 'Logs de Acesso PII',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LGPDConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('essential', 'Essencial para prestação de serviço'), ('support', 'Suporte técnico e atendimento'), ('communication', 'Comunicações e notificações'), ('marketing', 'Marketing e promoções'), ('analytics', 'Analytics e melhoria de serviço'), ('third_party', 'Compartilhamento com terceiros'), ('profiling', 'Análise de perfil e personalização')], max_length=30, verbose_name='Finalidade')),
                ('granted', models.BooleanField(default=False, verbose_name='Consentimento concedido')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do consentimento')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('legal_basis', models.CharField(choices=[('consent', 'Consentimento do titular'), ('contract', 'Execução de contrato'), ('legal_obligation', 'Obrigação legal'), ('legitimate_interest', 'Interesse legítimo'), ('vital_interest', 'Proteção da vida'), ('public_policy', 'Políticas públicas')], default='consent', max_length=50, verbose_name='Base legal')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versão dos termos')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do consentimento')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da revogação')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de expiração')),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='LGPDDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Acesso aos dados pessoais'), ('portability', 'Portabilidade dos dados'), ('correction', 'Correção de dados'), ('deletion', 'Exclusão de dados (direito ao esquecimento)'), ('restriction', 'Restrição de tratamento'), ('objection', 'Oposição ao tratamento'), ('revoke_consent', 'Revogação de consentimento')], max_length=20, verbose_name='Tipo de solicitação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/justificativa')),
                ('response', models.TextField(blank=True, verbose_name='Resposta ao titular')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da solicitação')),
                ('export_file', models.FileField(blank=True, null=True, upload_to='lgpd/exports/%Y/%m/', verbose_name='Arquivo de exportação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('deadline', models.DateTimeField(blank=True, help_text='Prazo de 15 dias úteis para resposta (LGPD Art. 18 §5)', null=True, verbose_name='Prazo legal')),
            ],
            options={
                'verbose_name': 'Solicitação LGPD',
                'verbose_name_plural': 'Solicitações LGPD',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='categoriafinanceira',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='itematendimento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='itematendimento',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='itematendimento',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='produto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='produto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete — registro não é removido do banco', verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='agentleaderboard',
            name='avg_resolution_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='agentleaderboard',
            name='avg_satisfaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='agentleaderboard',
            name='first_response_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% respondidos dentro do SLA', max_digits=5),
        ),
        migrations.AlterField(
            model_name='agentleaderboard',
            name='periodo',
            field=models.CharField(db_index=True, help_text='YYYY-MM', max_length=7),
        ),
        migrations.AlterField(
            model_name='agentleaderboard',
            name='rank',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='alertakpi',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Limite'),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], db_index=True, default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbotanalytics',
            name='satisfacao_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Satisfação Média'),
        ),
        migrations.AlterField(
            model_name='chatbotanalytics',
            name='tempo_resposta_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tempo Resposta Médio (s)'),
        ),
        migrations.AlterField(
            model_name='chatbotknowledgebase',
            name='confianca',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Nível de Confiança'),
        ),
        migrations.AlterField(
            model_name='chatbotmessage',
            name='confianca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Confiança da Resposta'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas'), ('general', 'Geral'), ('group', 'Grupo'), ('private', 'Privado')], db_index=True, default='support', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('closed', 'Fechado'), ('archived', 'Arquivado')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], db_index=True, default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerhealthscore',
            name='escalation_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customerhealthscore',
            name='resolution_time_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customerhealthscore',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], db_index=True, default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerhealthscore',
            name='satisfaction_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customerhealthscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=100, help_text='0-100, onde 100 = saudavel', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customerhealthscore',
            name='ticket_frequency_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='executivedashboardkpi',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atual'),
        ),
        migrations.AlterField(
            model_name='executivedashboardkpi',
            name='target_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_pagamento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='celular',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500),
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='kpialert',
            name='threshold',
            field=models.DecimalField(decimal_places=2, help_text='Valor limite para disparo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='data_movimentacao',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_ticket', 'Novo Ticket'), ('ticket_assigned', 'Ticket Atribuído'), ('ticket_status_change', 'Mudança de Status'), ('sla_warning', 'Alerta de SLA'), ('sla_breach', 'SLA Violado'), ('new_interaction', 'Nova Interação'), ('system_alert', 'Alerta do Sistema')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push Notification')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('bounced', 'Rejeitado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='perfilagente',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('ocupado', 'Ocupado'), ('ausente', 'Ausente'), ('offline', 'Offline')], db_index=True, default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cep',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='endereco',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone_alternativo',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Telefone Alternativo'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='celular',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, verbose_name='Celular / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_cpf',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_telefone',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='slaalert',
            name='alert_type',
            field=models.CharField(choices=[('warning', 'Alerta de Prazo'), ('breach', 'Violação de SLA'), ('escalation', 'Escalação Necessária'), ('resolved', 'SLA Cumprido')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='slahistory',
            name='status',
            field=models.CharField(choices=[('on_track', 'No Prazo'), ('warning', 'Alerta'), ('breached', 'Violado'), ('escalated', 'Escalado'), ('completed', 'Concluído')], db_index=True, default='on_track', max_length=15),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='warning_percentage',
            field=models.IntegerField(default=80, help_text='% do tempo SLA para enviar alerta', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='slaviolation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='slaviolation',
            name='severity',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='slaviolation',
            name='violation_type',
            field=models.CharField(choices=[('deadline_missed', 'Prazo Perdido'), ('escalation_failed', 'Falha na Escalação'), ('response_delayed', 'Resposta Atrasada')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='avg_resolution_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='em horas', max_digits=8),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='customer_satisfaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemmetrics',
            name='sla_compliance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='whatsappanalytics',
            name='tempo_resposta_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tempo Resposta Médio (min)'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprovado'), ('pending', 'Pendente'), ('rejected', 'Rejeitado'), ('disabled', 'Desabilitado')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='trigger_event',
            field=models.CharField(choices=[('ticket_created', 'Ticket Criado'), ('ticket_updated', 'Ticket Atualizado'), ('status_changed', 'Status Alterado'), ('agent_assigned', 'Agente Atribuído'), ('interaction_added', 'Interação Adicionada'), ('sla_warning', 'Aviso de SLA'), ('sla_breach', 'Violação de SLA')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='estoquealerta',
            index=models.Index(fields=['tipo_alerta', 'resolvido'], name='dashboard_e_tipo_al_75f1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo'], name='dashboard_p_tipo_065bf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentleaderboard',
            constraint=models.CheckConstraint(condition=models.Q(('first_response_rate__gte', 0), ('first_response_rate__lte', 100)), name='leaderboard_frr_0_100'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(condition=models.Q(('rate_limit__gt', 0)), name='apikey_rate_limit_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaosatisfacao',
            constraint=models.CheckConstraint(condition=models.Q(('nota_atendimento__gte', 1), ('nota_atendimento__lte', 5)), name='avaliacao_nota_atend_1_5'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaosatisfacao',
            constraint=models.CheckConstraint(condition=models.Q(('nota_resolucao__gte', 1), ('nota_resolucao__lte', 5)), name='avaliacao_nota_resolucao_1_5'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaosatisfacao',
            constraint=models.CheckConstraint(condition=models.Q(('nota_tempo__gte', 1), ('nota_tempo__lte', 5)), name='avaliacao_nota_tempo_1_5'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.CheckConstraint(condition=models.Q(('orcamento_mensal__gte', 0)), name='cc_orcamento_mensal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.CheckConstraint(condition=models.Q(('orcamento_anual__gte', 0)), name='cc_orcamento_anual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.CheckConstraint(condition=models.Q(('alerta_percentual__gte', 0), ('alerta_percentual__lte', 100)), name='cc_alerta_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('valor_mensal__gte', Decimal('0.01'))), name='contrato_valor_mensal_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='customerhealthscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='health_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='customerhealthscore',
            constraint=models.CheckConstraint(condition=models.Q(('ticket_frequency_score__gte', 0), ('ticket_frequency_score__lte', 100)), name='health_ticket_freq_0_100'),
        ),
        migrations.AddConstraint(
            model_name='customerhealthscore',
            constraint=models.CheckConstraint(condition=models.Q(('satisfaction_score__gte', 0), ('satisfaction_score__lte', 100)), name='health_satisfaction_0_100'),
        ),
        migrations.AddConstraint(
            model_name='customerhealthscore',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_time_score__gte', 0), ('resolution_time_score__lte', 100)), name='health_resolution_0_100'),
        ),
        migrations.AddConstraint(
            model_name='customerhealthscore',
            constraint=models.CheckConstraint(condition=models.Q(('escalation_score__gte', 0), ('escalation_score__lte', 100)), name='health_escalation_0_100'),
        ),
        migrations.AddConstraint(
            model_name='escalationlevel',
            constraint=models.CheckConstraint(condition=models.Q(('timeout_minutos__gt', 0)), name='escalation_timeout_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', Decimal('0.01'))), name='fatura_valor_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='itematendimento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_atend_quantidade_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='itematendimento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='item_atend_valor_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='itematendimento',
            constraint=models.CheckConstraint(condition=models.Q(('desconto_percentual__gte', 0), ('desconto_percentual__lte', 100)), name='item_atend_desconto_0_100'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='kb_view_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('helpful_votes__gte', 0)), name='kb_helpful_votes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.CheckConstraint(condition=models.Q(('unhelpful_votes__gte', 0)), name='kb_unhelpful_votes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='mov_estoque_quantidade_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='mov_estoque_valor_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='mov_estoque_valor_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', Decimal('0.01'))), name='mov_financeira_valor_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__gte', Decimal('0.01'))), name='pagamento_valor_pago_gte_001'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_custo__gte', 0)), name='produto_preco_custo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_venda__gte', 0)), name='produto_preco_venda_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_minimo__gte', 0)), name='produto_estoque_minimo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_maximo__gte', 0)), name='produto_estoque_maximo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 0)), name='produto_peso_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('altura__gte', 0)), name='produto_altura_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('largura__gte', 0)), name='produto_largura_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('profundidade__gte', 0)), name='produto_profundidade_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('first_response_time__gt', 0)), name='sla_first_response_time_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_time__gt', 0)), name='sla_resolution_time_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('escalation_time__gt', 0)), name='sla_escalation_time_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('warning_percentage__gte', 0), ('warning_percentage__lte', 100)), name='sla_warning_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('failure_count__gte', 0)), name='webhook_failure_count_gte_0'),
        ),
        migrations.AddField(
            model_name='lgpdaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lgpd_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que acessou'),
        ),
        migrations.AddField(
            model_name='lgpdconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgpd_consents', to=settings.AUTH_USER_MODEL, verbose_name='Titular dos dados'),
        ),
        migrations.AddField(
            model_name='lgpddatarequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lgpd_requests_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processado por'),
        ),
        migrations.AddField(
            model_name='lgpddatarequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgpd_requests', to=settings.AUTH_USER_MODEL, verbose_name='Titular dos dados'),
        ),
        migrations.AddIndex(
            model_name='lgpdaccesslog',
            index=models.Index(fields=['user', '-timestamp'], name='dashboard_l_user_id_c7e82c_idx'),
        ),
        migrations.AddIndex(
            model_name='lgpdaccesslog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='dashboard_l_resourc_fa889c_idx'),
        ),
        migrations.AddIndex(
            model_name='lgpdaccesslog',
            index=models.Index(fields=['action', '-timestamp'], name='dashboard_l_action_bca878_idx'),
        ),
        migrations.AddIndex(
            model_name='lgpdconsent',
            index=models.Index(fields=['user', 'purpose'], name='dashboard_l_user_id_38d88c_idx'),
        ),
        migrations.AddIndex(
            model_name='lgpdconsent',
            index=models.Index(fields=['granted', '-granted_at'], name='dashboard_l_granted_e44ad9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lgpdconsent',
            unique_together={('user', 'purpose', 'version')},
        ),
        migrations.AddIndex(
            model_name='lgpddatarequest',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_l_user_id_ab7571_idx'),
        ),
        migrations.AddIndex(
            model_name='lgpddatarequest',
            index=models.Index(fields=['status', 'request_type'], name='dashboard_l_status_bc2189_idx'),
        ),
    ]
