# Generated by Django 5.2.6 on 2026-02-23 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_lgpdaccesslog_lgpdconsent_lgpddatarequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='help', max_length=50)),
                ('cor', models.CharField(default='#e91e63', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Conhecimento',
                'verbose_name_plural': 'Categorias de Conhecimento',
                'db_table': 'dashboard_categoriaconhecimento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('resumo', models.TextField(blank=True, help_text='Resumo curto para listagem')),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('util_sim', models.IntegerField(default=0)),
                ('util_nao', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publico', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, help_text='Exibir como artigo destaque')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos_conhecimento', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='dashboard.categoriaconhecimento')),
            ],
            options={
                'verbose_name': 'Artigo de Conhecimento',
                'verbose_name_plural': 'Artigos de Conhecimento',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['publico', '-criado_em'], name='dashboard_a_publico_b74aa6_idx'), models.Index(fields=['categoria', '-visualizacoes'], name='dashboard_a_categor_a5cc88_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('visualizacoes__gte', 0)), name='artigo_visualizacoes_gte_0'), models.CheckConstraint(condition=models.Q(('util_sim__gte', 0)), name='artigo_util_sim_gte_0'), models.CheckConstraint(condition=models.Q(('util_nao__gte', 0)), name='artigo_util_nao_gte_0')],
            },
        ),
    ]
