# Generated by Django 5.2.6 on 2026-02-23 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_categoriaconhecimento_artigoconhecimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_abertos', models.IntegerField(default=0)),
                ('capacidade_maxima', models.IntegerField(default=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('ultima_atribuicao', models.DateTimeField(blank=True, null=True)),
                ('agente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegraAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('prioridade', models.CharField(blank=True, max_length=20)),
                ('palavras_chave', models.TextField(blank=True, help_text='Uma por linha')),
                ('skill_requerida', models.CharField(blank=True, max_length=100)),
                ('nivel_minimo', models.IntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
                ('prioridade_regra', models.IntegerField(default=0)),
                ('agente_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prioridade_regra'],
            },
        ),
        migrations.CreateModel(
            name='SkillAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado')])),
                ('certificado', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agente', 'skill')},
            },
        ),
    ]
