# Generated by Django 5.2.6 on 2026-02-23 04:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_cargotrabalho_regraatribuicao_skillagent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAlertaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamados_limiar', models.PositiveIntegerField(default=3, help_text='Gerar alerta quando equipamento atingir X chamados no período', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Chamados para Alerta')),
                ('chamados_periodo_dias', models.PositiveIntegerField(default=30, help_text='Período em dias para contagem de chamados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Período (dias)')),
                ('trocas_limiar', models.PositiveIntegerField(default=2, help_text='Gerar alerta quando equipamento for trocado X vezes no período', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Trocas para Alerta')),
                ('trocas_periodo_dias', models.PositiveIntegerField(default=90, help_text='Período em dias para contagem de trocas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Período de Trocas (dias)')),
                ('garantia_dias_aviso', models.PositiveIntegerField(default=30, help_text='Alertar X dias antes do vencimento da garantia', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aviso de Garantia (dias)')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alertas',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, help_text='Identificador único do equipamento', max_length=100, unique=True, verbose_name='Número de Série')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('tipo', models.CharField(db_index=True, help_text='Ex: Roteador, Switch, ONT, Cabo, OLT, etc.', max_length=100, verbose_name='Tipo de Equipamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('patrimonio', models.CharField(blank=True, help_text='Código interno de patrimônio', max_length=50, verbose_name='Nº Patrimônio')),
                ('local_instalacao', models.CharField(blank=True, help_text='Detalhamento: sala, rack, posição', max_length=200, verbose_name='Local de Instalação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_manutencao', 'Em Manutenção'), ('desativado', 'Desativado'), ('em_estoque', 'Em Estoque')], db_index=True, default='em_estoque', max_length=20)),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('data_garantia', models.DateField(blank=True, null=True, verbose_name='Garantia até')),
                ('data_desativacao', models.DateField(blank=True, null=True, verbose_name='Desativado em')),
                ('total_chamados', models.PositiveIntegerField(default=0, editable=False)),
                ('total_trocas', models.PositiveIntegerField(default=0, editable=False)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente onde o equipamento está instalado (vazio = em estoque)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='dashboard.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('excesso_chamados', 'Excesso de Chamados'), ('troca_frequente', 'Troca Frequente'), ('garantia_vencendo', 'Garantia Vencendo')], db_index=True, max_length=30)),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('valor_atual', models.IntegerField(default=0, help_text='Ex: quantidade de chamados que disparou o alerta', verbose_name='Valor Atual')),
                ('limiar', models.IntegerField(default=3, help_text='Limite configurado para este tipo de alerta', verbose_name='Limiar')),
                ('resolvido', models.BooleanField(db_index=True, default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('acao_tomada', models.TextField(blank=True, verbose_name='Ação Tomada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_equipamento_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='dashboard.equipamento')),
            ],
            options={
                'verbose_name': 'Alerta de Equipamento',
                'verbose_name_plural': 'Alertas de Equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='equipamento',
            field=models.ForeignKey(blank=True, help_text='Equipamento relacionado a este chamado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='dashboard.equipamento'),
        ),
        migrations.CreateModel(
            name='HistoricoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('instalacao', 'Instalação'), ('troca', 'Troca'), ('retirada', 'Retirada'), ('manutencao', 'Manutenção'), ('devolucao', 'Devolução ao Estoque')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('realizado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Realizado em')),
                ('cliente_anterior', models.ForeignKey(blank=True, help_text='Cliente de onde o equipamento saiu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_equipamento_saida', to='dashboard.cliente')),
                ('cliente_novo', models.ForeignKey(blank=True, help_text='Cliente para onde o equipamento foi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_equipamento_entrada', to='dashboard.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='dashboard.equipamento')),
                ('equipamento_substituido', models.ForeignKey(blank=True, help_text='Equipamento antigo que foi substituído (em caso de troca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituido_por', to='dashboard.equipamento')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_equipamento_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, help_text='Chamado que originou esta movimentação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_equipamento', to='dashboard.ticket')),
            ],
            options={
                'verbose_name': 'Histórico de Equipamento',
                'verbose_name_plural': 'Histórico de Equipamentos',
                'ordering': ['-realizado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['cliente', 'status'], name='idx_equip_cliente_status'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['tipo', 'status'], name='idx_equip_tipo_status'),
        ),
        migrations.AddIndex(
            model_name='alertaequipamento',
            index=models.Index(fields=['resolvido', '-criado_em'], name='idx_alerta_equip_pend'),
        ),
    ]
