# Generated by Django 5.2.6 on 2026-02-23 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_equipamentos_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Provedor')),
                ('slug', models.SlugField(help_text='Identificador único (ex: azure-ad, google)', unique=True)),
                ('protocol', models.CharField(choices=[('oidc', 'OpenID Connect'), ('saml', 'SAML 2.0')], default='oidc', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_class', models.CharField(default='fas fa-key', help_text='Ícone FontAwesome', max_length=50)),
                ('button_color', models.CharField(default='#4285F4', help_text='Cor do botão', max_length=7)),
                ('client_id', models.CharField(blank=True, max_length=500, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='Armazenado criptografado', max_length=500, verbose_name='Client Secret')),
                ('authorization_url', models.URLField(blank=True, verbose_name='Authorization Endpoint')),
                ('token_url', models.URLField(blank=True, verbose_name='Token Endpoint')),
                ('userinfo_url', models.URLField(blank=True, verbose_name='UserInfo Endpoint')),
                ('jwks_url', models.URLField(blank=True, verbose_name='JWKS URL')),
                ('scopes', models.CharField(default='openid email profile', help_text='Escopos separados por espaço', max_length=200)),
                ('saml_entity_id', models.CharField(blank=True, max_length=500, verbose_name='IdP Entity ID')),
                ('saml_sso_url', models.URLField(blank=True, verbose_name='IdP SSO URL')),
                ('saml_slo_url', models.URLField(blank=True, verbose_name='IdP SLO URL')),
                ('saml_certificate', models.TextField(blank=True, verbose_name='IdP X.509 Certificate')),
                ('attr_email', models.CharField(default='email', help_text='Nome do atributo para email', max_length=100)),
                ('attr_first_name', models.CharField(default='given_name', help_text='Nome do atributo para primeiro nome', max_length=100)),
                ('attr_last_name', models.CharField(default='family_name', help_text='Nome do atributo para sobrenome', max_length=100)),
                ('attr_username', models.CharField(default='preferred_username', help_text='Nome do atributo para username', max_length=100)),
                ('auto_create_user', models.BooleanField(default=True, help_text='Criar usuário automaticamente no primeiro login')),
                ('auto_update_user', models.BooleanField(default=True, help_text='Atualizar dados do usuário a cada login')),
                ('default_role', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('agente', 'Agente'), ('cliente', 'Cliente')], default='agente', max_length=20)),
                ('domain_whitelist', models.TextField(blank=True, help_text='Domínios permitidos (um por linha). Vazio = qualquer domínio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provedor SSO',
                'verbose_name_plural': 'Provedores SSO',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSOLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ssoprovider')),
            ],
            options={
                'verbose_name': 'Log de Login SSO',
                'verbose_name_plural': 'Logs de Login SSO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('nonce', models.CharField(blank=True, max_length=128)),
                ('redirect_url', models.CharField(default='/', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ssoprovider')),
            ],
            options={
                'verbose_name': 'Sessão SSO',
                'verbose_name_plural': 'Sessões SSO',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Organização')),
                ('slug', models.SlugField(help_text='Identificador único (subdomínio)', max_length=80, unique=True, verbose_name='Slug')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Domínio personalizado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Plano')),
                ('max_agents', models.PositiveIntegerField(default=3, verbose_name='Máx. agentes')),
                ('max_tickets_month', models.PositiveIntegerField(default=100, verbose_name='Máx. tickets/mês')),
                ('primary_color', models.CharField(default='#7c3aed', max_length=7, verbose_name='Cor primária')),
                ('secondary_color', models.CharField(default='#10b981', max_length=7, verbose_name='Cor secundária')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('agent', 'Agente'), ('viewer', 'Visualizador')], default='agent', max_length=20, verbose_name='Papel')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='dashboard.tenant')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('agent', 'Agente'), ('viewer', 'Visualizador')], default='agent', max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dashboard.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Organização',
                'verbose_name_plural': 'Membros da Organização',
                'ordering': ['tenant', '-role'],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
