# Generated by Django 5.2.6 on 2026-02-24 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_ssoprovider_ssologinlog_ssosession_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipamento',
            name='idx_equip_cliente_status',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicoequipamento',
            name='cliente_anterior',
        ),
        migrations.RemoveField(
            model_name='historicoequipamento',
            name='cliente_novo',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ponto_de_venda',
            field=models.ForeignKey(blank=True, help_text='Ponto de venda onde o equipamento está instalado (vazio = em estoque)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='dashboard.pontodevenda', verbose_name='Ponto de Venda'),
        ),
        migrations.AddField(
            model_name='historicoequipamento',
            name='pdv_anterior',
            field=models.ForeignKey(blank=True, help_text='Ponto de venda de onde o equipamento saiu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_equipamento_saida', to='dashboard.pontodevenda', verbose_name='PdV Anterior'),
        ),
        migrations.AddField(
            model_name='historicoequipamento',
            name='pdv_novo',
            field=models.ForeignKey(blank=True, help_text='Ponto de venda para onde o equipamento foi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_equipamento_entrada', to='dashboard.pontodevenda', verbose_name='PdV Novo'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária deste ponto de venda', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_de_venda', to='dashboard.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ponto_de_venda',
            field=models.ForeignKey(blank=True, help_text='Unidade/filial onde o atendimento ocorre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='dashboard.pontodevenda', verbose_name='Ponto de Venda'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('tecnico_senior', 'Técnico Sênior'), ('agente', 'Agente'), ('financeiro', 'Financeiro'), ('visualizador', 'Visualizador'), ('cliente', 'Cliente')], default='agente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['ponto_de_venda', 'status'], name='idx_equip_pdv_status'),
        ),
    ]
