# Generated by Django 5.2.6 on 2026-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_equipamento_idx_equip_cliente_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsável - Cargo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Responsável - E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável - Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=500, verbose_name='Responsável - Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(blank=True, help_text='Ex: Financeiro, Varejo, Saúde, Tecnologia', max_length=100, verbose_name='Segmento / Ramo de Atividade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Celular / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa (legado)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome / Razão Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Telefone'),
        ),
    ]
