# Generated by Django 5.2.6 on 2026-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_cliente_ativo_cliente_atualizado_em_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='responsavel_cargo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='responsavel_email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='responsavel_nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='responsavel_telefone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='website',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail de Contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(blank=True, help_text='Ex: Financeiro, Varejo, Saúde, Tecnologia', max_length=100, verbose_name='Segmento / Ramo'),
        ),
    ]
