# Generated by Django 6.0.2 on 2026-02-24 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_cliente_bairro_remove_cliente_celular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'prioridade', 'criado_em'], name='idx_ticket_status_prio_data'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'agente', 'criado_em'], name='idx_ticket_status_agente_data'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['cliente', 'status', 'criado_em'], name='idx_ticket_cliente_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'sla_deadline'], name='idx_ticket_status_sla'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['categoria', 'status'], name='idx_ticket_categoria_status'),
        ),
    ]
