# Generated by Django 5.2.6 on 2026-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_add_ticket_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_rede',
            field=models.CharField(blank=True, default='', db_index=True, help_text='Código da rede na planilha (ex: 104-0021)', max_length=20, verbose_name='Código Rede'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='cod_rede',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código Rede'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='cod_regional',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código Regional'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='rede',
            field=models.CharField(blank=True, default='', help_text='Nome da rede (ex: REDE - GRANDE SAO PAULO)', max_length=100, verbose_name='Rede'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='regional',
            field=models.CharField(blank=True, default='', help_text='Nome da regional (ex: REG SP CENTRO-NORTE)', max_length=100, verbose_name='Regional'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='status_unidade',
            field=models.CharField(blank=True, default='Ativo', help_text='Status operacional: Ativo, Virtual, Encerrado, etc.', max_length=30, verbose_name='Status Unidade'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='tipo',
            field=models.CharField(blank=True, default='', help_text='Tipo da unidade: AG, PAB, PAE, Store, etc.', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='pontodevenda',
            name='uniorg',
            field=models.CharField(blank=True, default='', db_index=True, help_text='Código da unidade organizacional (ex: 001-0001)', max_length=20, verbose_name='UNIORG'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='bairro',
            field=models.CharField(blank=True, max_length=60, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='celular',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Celular / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='cnpj',
            field=models.CharField(max_length=25, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='email_principal',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail principal'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_cargo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Cargo / Função'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_cpf',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Responsável'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_telefone',
            field=models.CharField(blank=True, help_text='Criptografado em repouso', max_length=500, verbose_name='Telefone do Responsável'),
        ),
    ]
