# Generated by Django 5.2.11 on 2026-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_add_ticket_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaviolation',
            name='time_exceeded',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
