# Generated by Django 5.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_cliente_cod_rede_pontodevenda_cod_rede_and_more'),
        ('dashboard', '0036_sla_violation_time_exceeded_nullable'),
    ]

    operations = [
    ]
