# Generated by Django 5.2.11 on 2026-03-04 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_merge_0036_conflicting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail de Contato'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='bairro',
            field=models.CharField(max_length=60, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='celular',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, verbose_name='Celular / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='cidade',
            field=models.CharField(max_length=60, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='email_principal',
            field=models.EmailField(max_length=254, verbose_name='E-mail principal'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='logradouro',
            field=models.CharField(max_length=120, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='razao_social',
            field=models.CharField(max_length=150, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_cargo',
            field=models.CharField(max_length=60, verbose_name='Cargo / Função'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_cpf',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='pontodevenda',
            name='responsavel_telefone',
            field=models.CharField(help_text='Criptografado em repouso', max_length=500, verbose_name='Telefone do Responsável'),
        ),
        migrations.CreateModel(
            name='RegistroVigilante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('implantacao', 'Implantação'), ('pronta-resposta', 'Pronta Resposta')], db_index=True, max_length=20)),
                ('empresa', models.CharField(db_index=True, max_length=100)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('duracao_minutos', models.FloatField(verbose_name='Duração (minutos)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhamento do cálculo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_vigilante_criados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_vigilante', to='dashboard.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Registro de Vigilante',
                'verbose_name_plural': 'Registros de Vigilante',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'criado_em'], name='dashboard_r_tipo_428312_idx'), models.Index(fields=['empresa', 'uf'], name='dashboard_r_empresa_3a2a58_idx')],
            },
        ),
    ]
