# Generated by Django 5.2.11 on 2026-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_registro_vigilante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subtipo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subtipo'),
        ),
    ]
