# Generated by Django 5.2.11 on 2026-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_ticket_subtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('remoto', 'Remoto'), ('venda', 'Venda')], default='corretiva', max_length=15),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='tipo',
            field=models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva'), ('remoto', 'Remoto'), ('venda', 'Venda')], default='corretiva', max_length=15),
        ),
    ]
