# Generated by Django 5.2.11 on 2026-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_ticket_tipo_alter_tickettemplate_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovigilante',
            name='duracao_minutos',
            field=models.FloatField(blank=True, null=True, verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='registrovigilante',
            name='fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Fim'),
        ),
        migrations.AlterField(
            model_name='registrovigilante',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor (R$)'),
        ),
    ]
