# Generated by Django 5.2.6 on 2026-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_registrovigilante_duracao_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sintoma',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sintoma'),
        ),
    ]
