# Generated by Django 5.2.6 on 2026-03-05 20:20

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_ticket_sintoma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_locacao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de locação mensal (LPU)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_locacao__gte', 0)), name='produto_preco_locacao_gte_0'),
        ),
    ]
